apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reports.fullname" . }}
  labels: {{ include "reports.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        autoindex on;

        # Enable CORS from https://jenkins.io and https://jenkins-ci.org
        #
        if ($http_origin ~ '^https://(jenkins\.io|jenkins-ci\.org)$') {
          add_header Access-Control-Allow-Origin      $http_origin;
          add_header Access-Control-Allow-Credentials true;
          add_header Access-Control-Allow-Headers     $http_access_control_request_headers;
          add_header Access-Control-Allow-Methods     $http_access_control_request_method;
        }
      }
    }