apiVersion: v1
kind: Service
metadata:
  name: {{ include "reports.fullname" . }}
  labels: {{ include "reports.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80

  selector:
    app.kubernetes.io/name: {{ include "reports.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
