apiVersion: v2
name: mirrorbits-parent
description: A mirrorbits parent chart for Kubernetes
type: application
version: 0.2.6
dependencies:
- name: mirrorbits-lite
  condition: mirrorbits-lite.enabled
  repository: https://jenkins-infra.github.io/helm-charts
  version: 0.3.1
- name: httpd
  condition: httpd.enabled
  repository: https://jenkins-infra.github.io/helm-charts
  version: 0.2.1
- name: rsyncd
  condition: rsyncd.enabled
  repository: https://jenkins-infra.github.io/helm-charts
  version: 1.3.2
