apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkinsio.fullname" . }}
  labels: {{ include "jenkinsio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ include "jenkinsio.fullname" . }}
      protocol: TCP
      targetPort: {{ include "jenkinsio.fullname" . }}
      port: 80

  selector:
    app.kubernetes.io/name: {{ include "jenkinsio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
