{{- if (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wiki.fullname" . }}
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
spec:
  {{- with .Values.poddisruptionbudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.poddisruptionbudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "wiki.fullname" . }}
{{- end }}
