{{ if .Values.corePackages.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: corePackages
type: Opaque
data:
  azurestorageaccountname: {{ .Values.corePackages.storageAccountName }}
  azurestorageaccountkey: {{ .Values.corePackages.storageAccountKey }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: corePackages
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: corePackages
    shareName: {{ .Values.corePackages.shareName }}
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corePackages
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi
{{ end }}
