---
apiVersion: v1
kind: Secret
metadata:
  # Jenkins ID
  name: "jenkins-secrets"
type: Opaque
data:
  # UTF-8 base64 encoded
  LDAP_SERVER: {{ .Values.ldap_server | b64enc }}
  LDAP_ROOT_DN: {{ .Values.ldap_root_dn | b64enc }}
  LDAP_MANAGER_DN: {{ .Values.ldap_manager_dn | b64enc }}
  LDAP_MANAGER_PASSWORD: {{ .Values.ldap_manager_password | b64enc }}
