---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pkg.fullname" . }}-binary
  labels:
    data: pkg-binary
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: {{ include "pkg.fullname" . }}-binary
    shareName: {{ .Values.corePackages.binary.shareName }}
    readOnly: true
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=101
  - gid=101
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pkg.fullname" . }}-website
  labels:
    data: pkg-website
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: {{ include "pkg.fullname" . }}-website
    shareName: {{ .Values.corePackages.website.shareName }}
    readOnly: true
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=101
  - gid=101
  - mfsymlinks
  - nobrl
