---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pkg.fullname" . }}-binary
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      data: pkg-binary

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pkg.fullname" . }}-website
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      data: pkg-website
