---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pkg.fullname" . }}-binary
type: Opaque
data:
  azurestorageaccountname: {{ .Values.corePackages.binary.storageAccountName }}
  azurestorageaccountkey: {{ .Values.corePackages.binary.storageAccountKey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pkg.fullname" . }}-website
type: Opaque
data:
  azurestorageaccountname: {{ .Values.corePackages.website.storageAccountName }}
  azurestorageaccountkey: {{ .Values.corePackages.website.storageAccountKey }}
