---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-site.fullname" . }}
  labels:
{{ include "plugin-site.labels" . | indent 4 }}
type: Opaque
data:
  github_client_id: {{ .Values.github.clientId | b64enc }}
  github_client_secret: {{ .Values.github.clientSecret | b64enc }}
{{ if .Values.azureStorageAccountName }}
  azurestorageaccountname: {{ .Values.azureStorageAccountName | b64enc }}
{{- end }}
{{ if .Values.azureStorageAccountKey }}
  azurestorageaccountkey: {{ .Values.azureStorageAccountKey | b64enc }}
{{- end }}
