apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-site.fullname" . }}
  labels: {{ include "plugin-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 8080
  selector:
    app.kubernetes.io/name: {{ include "plugin-site.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
