apiVersion: v1
kind: Service
metadata:
  name: {{ include "accountapp.fullname" . }}
  labels: {{ include "accountapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: frontend
      protocol: TCP
      targetPort: frontend
      port: 5000
    - name: backend
      protocol: TCP
      targetPort: backend
      port: 8080
  selector:
    app.kubernetes.io/name: {{ include "accountapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
