---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.jenkins.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.jenkins.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.jenkins.serviceAccount.name }}
