apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "charts-secrets"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "SSH private key used to clone jenkins-infra/charts-secrets"
type: Opaque
data:
# base64 encoded username
  username: {{ .Values.ssh_charts_secrets.username | b64enc }}
  privateKey: {{ .Values.ssh_charts_secrets.privkey | b64enc }}
