# Default values for plugins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


backend:
  replicaCount: 1
  image:
    repository: jenkinsciinfra/plugin-site-api
    tag: 133-b6e652
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi

frontend:
  replicaCount: 1
  image:
    repository: jenkinsciinfra/plugin-site
    tag: 122-bd2a5f
    oldMode: true
    #repository: halkeye/jenkins-plugin-site
    #tag: 44-14cfe6
    pullPolicy: IfNotPresent
  port: 80
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  #resources:
  #  limits:
  #    cpu: 100m
  #    memory: 64Mi
  #  requests:
  #    cpu: 100m
  #    memory: 64Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP

# Please define ingress settings into environment variable
ingress:
  enabled: disabled
  paths:
    - path: /api/(.*)
      port: backend
    - path: /(.*)
      port: frontend

#  annotations:
#    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
#    "kubernetes.io/ingress.class": "public-ingress"
#    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
#
#  hosts:
#    - host: plugins.jenkins.io
#
#  tls:
#    - secretName: plugins-tls
#      hosts:
#        - plugins.jenkins.io


nodeSelector: {}

tolerations: []

affinity: {}

dataFileUrl: https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/generate-data/lastSuccessfulBuild/artifact/plugins.json.gzip
restApiUrl: https://plugins.jenkins.io/api

github:
  clientId: ""
  clientSecret: ""
