---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incrementals-publisher.fullname" . }}
  labels:
{{ include "incrementals-publisher.labels" . | indent 4 }}
type: Opaque
data:
  artifactory_key: {{ .Values.artifactory.key | toString | b64enc }}
  github_token: {{ .Values.github.token | toString | b64enc }}
  github_app_id: {{ .Values.github.appId | toString | b64enc }}
  github_app_private_key: {{ .Values.github.privateKey | toString | b64enc }}
  jenkins_auth: {{ .Values.jenkins.auth | toString | b64enc }}
  preshared_key: {{ .Values.preshared_key | toString | b64enc }}
