  
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkinsio.fullname" . }}-zh
  labels: {{ include "jenkinsio.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
  
    {{- if .Values.forceJenkinsIoHost -}}
      if ( $host != 'jenkins.io') {
        return 301 $scheme://jenkins.io/zh/$request_uri;
      }
    {{- end }}
  
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
  
      error_page  404              /404/index.html;
  
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }