{{ if .Values.azureStorageAccountName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: javadoc
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azureStorageAccountName }}
  azurestorageaccountkey: {{ .Values.azureStorageAccountKey }}
{{- end }}