{{- if (gt (int .Values.replicaCount.files) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mirrorbits.fullname" . }}-files
  labels:
    {{- include "mirrorbits.labels" . | nindent 4 }}
spec:
  {{- with .Values.poddisruptionbudget.files.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.poddisruptionbudget.files.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mirrorbits.files.selectorLabels" . | nindent 6 }}
{{- end }}
