{{- if (gt (int .Values.replicaCount.rsyncd) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mirrorbits.fullname" . }}-rsyncd
  labels:
    {{- include "mirrorbits.labels" . | nindent 4 }}
spec:
  {{- with .Values.poddisruptionbudget.rsyncd.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.poddisruptionbudget.rsyncd.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mirrorbits.rsyncd.selectorLabels" . | nindent 6 }}
{{- end }}
