{{- if (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mirrorbits.fullname" . }}
  labels:
    {{- include "mirrorbits.labels" . | nindent 4 }}
spec:
  {{- with .Values.poddisruptionbudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.poddisruptionbudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mirrorbits.selectorLabels" . | nindent 6 }}
{{- end }}
