---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}
type: Opaque
data:
  mirrorbits.conf: {{ .Values.conf | b64enc }}
{{- if and .Values.geoipupdate.account_id .Values.geoipupdate.license_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-geoipupdate
type: Opaque
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geoipupdate.account_id | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geoipupdate.license_key | b64enc }}
{{- end }}
{{- if and .Values.repository.secrets.enabled (not (dig "global" "storage" "enabled" false .Values.AsMap)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-binary
type: Opaque
data:
  {{- range $key, $val := .Values.repository.secrets.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end -}}
