{{ if $.Values.persistent.secret.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.persistent.volumeClaim.name | default (printf "%s-binary" (include "mirror.fullname" .))  }}
type: Opaque
data:
{{ toYaml $.Values.persistent.secret.spec | nindent 2 }}
{{- end -}}
