# Default values for acme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
acme:
  id: "letsencrypt-prod"
  email: ""
  server: "https://acme-staging-v02.api.letsencrypt.org/directory"
  
  dns01:
      azure:
          clientID: ""
          clientSecretSecretRef:
              name: ""
              key: ""
          subscriptionID: ""
          tenantID: ""
          resourceGroupName: ""
          hostedZoneName: ""

