apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mirrorbits.fullname" . }}-files
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
  
      location / {
          autoindex on;
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page  404              /404/index.html;
  
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
  
    }
