---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mirrorbits.fullname" . }}-binary
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: azurefile
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      data: {{ include "mirrorbits.fullname" . }}-binary
