---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-binary
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.storageAccountKey | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}
type: Opaque
data:
  mirrorbits.conf: {{ .Values.mirrorbits.conf | b64enc }}
