apiVersion: v1
kind: ServiceAccount
metadata:
  name: ldap
  namespace: ldap

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: ldap
  name: ldap-access
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list","watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader-binding
  namespace: ldap
subjects:
- kind: ServiceAccount
  name: ldap
  namespace: ldap
- kind: ServiceAccount
  name: jx-dex
  namespace: jx
roleRef:
  kind: Role
  name: ldap-access
  apiGroup: rbac.authorization.k8s.io
