apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.acme.id }}
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: {{ .Values.acme.id }}
    # Enable the HTTP01 challenge mechanism for this Issuer
    http01: {}
