apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "github"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Default github credentials"
type: Opaque
stringData:
  username: {{ .Values.credentials.github.username }}
  password: {{ .Values.credentials.github.password }}
