jenkins:
    master:
        runAsUser: 1000
        fsGroup: 1000
        containerEnv:
          - name: SECRETS
            value: /var/jenkins_secrets
        overwritePlugins: true
        secretsFilesSecret: 'jenkins-secrets'
        serviceType: "ClusterIP"
        JCasC:
          enabled: true
          configScripts:
            jobs-settings: |
                jobs:
                  - script: >
                      multibranchPipelineJob('release-jenkins-core') {
                        displayName "Jenkins Core Releases"
                        description "Jenkins Core Releases"
                        branchSources {
                          github {
                            scanCredentialsId('github')
                            repoOwner('olblak')
                            repository('jenkins')
                            includes('master')
                          }
                        }
                        orphanedItemStrategy {
                          discardOldItems {
                            numToKeep(10)
                          }
                        }
                        triggers {
                          // Release every Sunday
                          cron('*/15 * * * 0')
                        }
                      }

            ldap-settings: |
                jenkins:
                  securityRealm:
                    ldap:
                      configurations:
                          - server: ldap.jenkins.io
                            rootDN: dc=jenkins-ci,dc=org
                            managerDN: "cn=admin,dc=jenkins-ci,dc=org"
                            managerPasswordSecret: "${LDAP_DN_PASSWORD}"
                            userSearch: cn={0}
                      cache:
                          size: 100
                          ttl: 300

            matrix-settings: |
                jenkins:
                  authorizationStrategy:
                    globalMatrix:
                      grantedPermissions:
                        - "Overall/Read:release"
                        - "Overall/Administer:jenkins-admins"
                        - "Overall/Administer:admins"
        installPlugins:
            - antisamy-markup-formatter
            - authentication-tokens
            - blueocean-autofavorite
            - blueocean-commons
            - blueocean-config
            - blueocean-core-js
            - blueocean-dashboard
            - blueocean-display-url
            - blueocean-events
            - blueocean-git-pipeline
            - blueocean-github-pipeline
            - blueocean-i18n
            - blueocean-jira
            - blueocean-jwt
            - blueocean-personalization
            - blueocean-pipeline-api-impl
            - blueocean-pipeline-editor
            - blueocean-pipeline-scm-api
            - blueocean-rest-impl
            - blueocean-rest
            - blueocean-web
            - blueocean
            - branch-api
            - build-name-setter
            - configuration-as-code
            - configuration-as-code-support
            - config-file-provider
            - credentials-binding
            - credentials
            - git-client
            - git
            - github-api
            - github-branch-source
            - github
            - jira
            - job-dsl
            - junit
            - kubernetes-credentials
            - kubernetes
            - kubernetes-credentials-provider
            - ldap
            - lockable-resources
            - pipeline-utility-steps
            - matrix-auth
            - matrix-project
            - pipeline-build-step
            - pipeline-graph-analysis
            - pipeline-input-step
            - pipeline-milestone-step
            - pipeline-model-api
            - pipeline-model-declarative-agent
            - pipeline-model-definition
            - pipeline-model-extensions
            - pipeline-rest-api
            - pipeline-stage-step
            - pipeline-stage-tags-metadata
            - pipeline-stage-view
            - plain-credentials
            - scm-api
            - script-security
            - ssh-agent
            - ssh-credentials
            - support-core
            - token-macro
            - variant
            - workflow-aggregator
            - workflow-api
            - workflow-basic-steps
            - workflow-cps-global-lib
            - workflow-cps
            - workflow-durable-task-step
            - workflow-job
            - workflow-multibranch
            - workflow-scm-step
            - workflow-step-api
            - workflow-support
            - javadoc
            - metrics
    agent:
        enabled: true
    serviceAccount:
        create: true
        name: jenkins-master
    serviceAccountAgent:
        create: true
        name: jenkins-agent
