apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polls.fullname" . }}
  labels:
{{ include "polls.labels" . | indent 4 }}
data:
  ldap_url: "{{ .Values.ldap.url }}"
  ldap_port: "{{ .Values.ldap.port }}"
  ldap_protocol: "{{ .Values.ldap.protocol }}"
  ldap_group_base_dn: "{{ .Values.ldap.group_base_dn }}"

