apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polls.fullname" . }}
  labels:
{{ include "polls.labels" . | indent 4 }}
type: Opaque
data:
  db_url: "{{ .Values.database.url | b64enc }}"
  ldap_bind_user: "{{ .Values.ldap.bind_user | b64enc }}"
  ldap_bind_password: "{{ .Values.ldap.bind_password | b64enc }}"
