apiVersion: v1
kind: Service
metadata:
  name: {{ include "polls.fullname" . }}-frontend
  labels:
{{ include "polls.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "polls.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
