# Default values for wiki2md.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

# Please define ingress settings into environment variable
#ingress:
#  enabled: true
#  annotations: 
#    "certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"
#    "kubernetes.io/ingress.class": "public-ingress"
#    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
#
#  hosts:
#    - host: wiki2md.jenkins.io
#      paths: 
#        - /
#
#  tls: []
#    - secretName: wiki2md-tls
#      hosts:
#        - wiki2md.jenkins.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
