apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rss2twitter.fullname" . }}
  labels:
    {{- include "rss2twitter.labels" . | nindent 4 }}
type: Opaque
data:
  twitterConsumerKey: ""
  twitterConsumerSecret: ""
  twitterAccessToken: ""
  twitterAccessSecret: ""
