apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rss2twitter.fullname" . }}
  labels:
    {{- include "rss2twitter.labels" . | nindent 4 }}
type: Opaque
data:
  TWI_CONSUMER_KEY: ""
  TWI_CONSUMER_SECRET: ""
  TWI_ACCESS_TOKEN: ""
  TWI_ACCESS_SECRET: ""
