---
name: Test Charts

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chart:
          - artifact-caching-proxy
          - httpredirector
          - jenkins-jobs
          - jenkins-kubernetes-agents
          - plugin-health-scoring
      fail-fast: false

    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1.7
        id: generate_token
        with:
          app_id: ${{ secrets.JENKINS_ADMIN_APP_ID }}
          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: install helm unittests
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest

      - name: run unit tests
        working-directory: ./charts/
        run: |
          helm unittest --helm3 "${{ matrix.chart }}"
