apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.tls }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
{{- end }}
    nginx.ingress.kubernetes.io/permanent-redirect: {{ .Values.urlredirect }}
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
  name: "{{ .Release.Name }}-{{ .Values.host }}"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.host }}
{{- if .Values.tls }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Release.Name }}-tls
{{- end }}
