{{ with .Values.storage.persistentVolume.azureFile -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits-parent.pv-secretname" $ }}
  labels:
{{ include "mirrorbits-parents.labels" $ | nindent 4 }}
type: Opaque
data:
  azurestorageaccountname: {{ .storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .storageAccountKey | b64enc }}
{{- end -}}
