{{ if and .Values.storage.persistentVolume.azureFile.storageAccountName .Values.storage.persistentVolume.azureFile.storageAccountKey -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits-parent.pv-secretname" . }}
  labels:
{{ include "mirrorbits-parents.labels" . | nindent 4 }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storage.persistentVolume.azureFile.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.storage.persistentVolume.azureFile.storageAccountKey | b64enc }}
{{- end -}}
