{{- if .Values.serviceaccount.enabled }}
# From https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/service-account.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mirrorbits-parent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{- if .Values.serviceaccount.enabled }}
# From https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/service-account.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "mirrorbits-parent.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
{{- end }}
---
{{- if .Values.serviceaccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "mirrorbits-parent.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "mirrorbits-parent.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "mirrorbits-parent.serviceAccountName" . }}
  namespace: {{ template "mirrorbits-parent.serviceAccountNamespace" . }}
{{- end }}
---
{{- if .Values.serviceaccount.enabled }}
# From https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mirrorbits-parent.serviceAccountName" . }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "mirrorbits-parent.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
